# Generated by Django 5.0.1 on 2024-11-27 13:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')])),
                ('destination', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')])),
            ],
            options={
                'db_table': 'call_records',
                'indexes': [models.Index(fields=['call_id'], name='call_record_call_id_0a6bcd_idx'), models.Index(fields=['source'], name='call_record_source_3f368f_idx'), models.Index(fields=['timestamp'], name='call_record_timesta_5a7b12_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'processed_calls',
                'indexes': [models.Index(fields=['source'], name='processed_c_source_9e8b04_idx'), models.Index(fields=['start_time'], name='processed_c_start_t_187293_idx'), models.Index(fields=['end_time'], name='processed_c_end_tim_4ea874_idx')],
            },
        ),
    ]
